using Microsoft.Data.SqlClient;
using SuvidhaPOS.Premium.Data;

namespace SuvidhaPOS.Premium;

public static class ReportTaxModules
{
    static SqlParameter P(string n, object? v) => new(n, v ?? DBNull.Value);
    public static void Map(WebApplication app)
    {
        app.MapGet("/api/taxes", async (Db db) => Results.Ok(await db.QueryAsync("SELECT Id,TaxName,Rate,IsDefault,IsActive FROM TaxMaster WHERE IsActive=1 ORDER BY IsDefault DESC,Rate,TaxName")));
        app.MapPost("/api/taxes", async (Db db, TaxRequest x) => { if (string.IsNullOrWhiteSpace(x.TaxName)||x.Rate<0||x.Rate>100)return Results.BadRequest(new{message="Valid tax name and rate (0-100) are required"}); var id=await db.ScalarAsync("INSERT TaxMaster(TaxName,Rate,IsDefault,IsActive) VALUES(@n,@r,0,1);SELECT CAST(SCOPE_IDENTITY() AS int)",P("@n",x.TaxName.Trim()),P("@r",x.Rate)); return Results.Ok(new{id}); });
        app.MapPut("/api/taxes/{id:int}", async (Db db,int id,TaxRequest x) => { if(string.IsNullOrWhiteSpace(x.TaxName)||x.Rate<0||x.Rate>100)return Results.BadRequest(new{message="Valid tax name and rate (0-100) are required"}); await db.ScalarAsync("UPDATE TaxMaster SET TaxName=@n,Rate=@r WHERE Id=@id AND IsDefault=0",P("@n",x.TaxName.Trim()),P("@r",x.Rate),P("@id",id)); return Results.Ok(new{updated=true}); });
        app.MapDelete("/api/taxes/{id:int}", async (Db db,int id) => { await db.ScalarAsync("UPDATE TaxMaster SET IsActive=0 WHERE Id=@id AND IsDefault=0",P("@id",id)); return Results.Ok(new{deleted=true}); });
        app.MapGet("/api/reports/catalog",()=>Results.Ok(new[]{
            new{Key="current-stock",Name="Current Stock",Group="Inventory"},new{Key="rack-stock",Name="Rack / Location Stock",Group="Inventory"},new{Key="stock-ledger",Name="Stock Ledger",Group="Inventory"},new{Key="item-sale",Name="Item-wise Sale",Group="Sales"},new{Key="sale",Name="Sales Register",Group="Sales"},new{Key="customer-sale",Name="Customer-wise Sale",Group="Sales"},new{Key="customer-ledger",Name="Customer Ledger",Group="Ledger"},new{Key="sales-return",Name="Sales Return",Group="Returns"},new{Key="item-purchase",Name="Item-wise Purchase",Group="Purchase"},new{Key="purchase",Name="Purchase Register",Group="Purchase"},new{Key="supplier-purchase",Name="Supplier-wise Purchase",Group="Purchase"},new{Key="supplier-ledger",Name="Supplier Ledger",Group="Ledger"},new{Key="purchase-return",Name="Purchase Return",Group="Returns"},new{Key="supplier-purchase-return",Name="Supplier-wise Purchase Return",Group="Returns"},new{Key="payment-register",Name="Payment Register",Group="Finance"},new{Key="gstr1",Name="GSTR-1 Sales",Group="GST"},new{Key="hsn-summary",Name="HSN / Taxable Summary",Group="GST"},new{Key="tax-summary",Name="GST / Tax Summary",Group="GST"},new{Key="expired",Name="Expired Items",Group="Expiry"},new{Key="close-expiry",Name="Close to Expiry",Group="Expiry"},new{Key="dead-stock",Name="Dead Stock",Group="Inventory"},new{Key="audit",Name="Audit Report",Group="Audit"},new{Key="expenses",Name="Expense Register",Group="Finance"},new{Key="profit-loss",Name="Profit & Loss",Group="Finance"},new{Key="day-closing",Name="Day Closing",Group="Finance"}
        }));
        app.MapGet("/api/reports/{type}",async(Db db,string type,DateTime? from,DateTime? to,int deadDays=90,int expiryDays=30,string? q=null,int? supplierId=null)=>{
            var f=(from??DateTime.Today).Date;var t=(to??DateTime.Today).Date;if(t<f)(f,t)=(t,f);var end=t.AddDays(1);var term=q?.Trim()??"";var like="%"+term+"%";var key=type.Trim().ToLowerInvariant();string sql;SqlParameter[] ps;
            switch(key){
                case "current-stock":sql=@"SELECT p.Id,p.Name,p.Barcode,p.Sku,p.Category,p.Unit,p.Hsn,p.GstRate,p.Mrp,p.PurchasePrice,p.SalePrice,p.LocationCode,p.RackName,p.ShelfName,CAST(ISNULL(SUM(b.Quantity),0) AS decimal(18,3)) Stock,CAST(ISNULL(SUM(b.Quantity*b.CostPrice),0) AS decimal(18,2)) StockValue,MIN(CASE WHEN b.Quantity>0 THEN b.ExpiryDate END) NearestExpiry FROM Products p LEFT JOIN ProductBatches b ON b.ProductId=p.Id WHERE p.IsActive=1 AND (@q='' OR p.Name LIKE @like OR ISNULL(p.Barcode,'') LIKE @like OR ISNULL(p.Sku,'') LIKE @like OR ISNULL(p.LocationCode,'') LIKE @like) GROUP BY p.Id,p.Name,p.Barcode,p.Sku,p.Category,p.Unit,p.Hsn,p.GstRate,p.Mrp,p.PurchasePrice,p.SalePrice,p.LocationCode,p.RackName,p.ShelfName ORDER BY p.Name";ps=new[]{P("@q",term),P("@like",like)};break;
                case "rack-stock":sql=@"SELECT ISNULL(NULLIF(p.LocationCode,''),ISNULL(p.RackName,'-')) RackLocation,p.Name,p.Barcode,p.Category,CAST(ISNULL(SUM(b.Quantity),0) AS decimal(18,3)) Stock,CAST(ISNULL(SUM(b.Quantity*b.CostPrice),0) AS decimal(18,2)) StockValue FROM Products p LEFT JOIN ProductBatches b ON b.ProductId=p.Id WHERE p.IsActive=1 AND (@q='' OR ISNULL(p.LocationCode,'') LIKE @like OR ISNULL(p.RackName,'') LIKE @like OR p.Name LIKE @like) GROUP BY ISNULL(NULLIF(p.LocationCode,''),ISNULL(p.RackName,'-')),p.Name,p.Barcode,p.Category ORDER BY RackLocation,p.Name";ps=new[]{P("@q",term),P("@like",like)};break;
                case "stock-ledger":sql=@"SELECT sl.CreatedAt,sl.MovementType,p.Name,p.Barcode,sl.Quantity,sl.ReferenceType,sl.ReferenceId,sl.Notes FROM StockLedger sl JOIN Products p ON p.Id=sl.ProductId WHERE sl.CreatedAt>=@f AND sl.CreatedAt<@e AND (@q='' OR p.Name LIKE @like OR ISNULL(p.Barcode,'') LIKE @like) ORDER BY sl.CreatedAt DESC";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "sale":sql=@"SELECT s.Id,s.InvoiceNo,s.BillDate,s.CustomerName,s.PaymentMode,s.SubTotal,s.Discount,s.Tax,s.GrandTotal,s.PaidAmount,s.Status FROM Sales s WHERE s.BillDate>=@f AND s.BillDate<@e AND (@q='' OR s.InvoiceNo LIKE @like OR s.CustomerName LIKE @like) ORDER BY s.BillDate DESC";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "item-sale":sql=@"SELECT s.BillDate,s.InvoiceNo,p.Name,p.Barcode,p.Category,sl.Quantity,sl.SalePrice,sl.TaxRate,CAST(sl.Quantity*sl.SalePrice-sl.Discount AS decimal(18,2)) TaxableValue,CAST((sl.Quantity*sl.SalePrice-sl.Discount)*sl.TaxRate/100 AS decimal(18,2)) TaxAmount,s.CustomerName FROM SaleLines sl JOIN Sales s ON s.Id=sl.SaleId JOIN Products p ON p.Id=sl.ProductId WHERE s.BillDate>=@f AND s.BillDate<@e AND s.Status='Completed' AND (@q='' OR p.Name LIKE @like OR ISNULL(p.Barcode,'') LIKE @like) ORDER BY s.BillDate DESC,p.Name";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "customer-sale":sql=@"SELECT s.CustomerName,COUNT(*) Bills,CAST(SUM(s.SubTotal) AS decimal(18,2)) SubTotal,CAST(SUM(s.Tax) AS decimal(18,2)) Tax,CAST(SUM(s.GrandTotal) AS decimal(18,2)) GrandTotal,CAST(SUM(s.PaidAmount) AS decimal(18,2)) Paid FROM Sales s WHERE s.BillDate>=@f AND s.BillDate<@e AND s.Status='Completed' GROUP BY s.CustomerName ORDER BY GrandTotal DESC";ps=new[]{P("@f",f),P("@e",end)};break;
                case "customer-ledger":sql=@"SELECT c.Name,c.Phone,CAST(c.OpeningBalance AS decimal(18,2)) OpeningBalance,CAST(ISNULL((SELECT SUM(s.GrandTotal) FROM Sales s WHERE s.CustomerId=c.Id AND s.BillDate>=@f AND s.BillDate<@e AND s.Status='Completed'),0) AS decimal(18,2)) Sales,CAST(ISNULL((SELECT SUM(cp.Amount) FROM CustomerPayments cp WHERE cp.CustomerId=c.Id AND cp.PaymentDate>=@f AND cp.PaymentDate<@e),0) AS decimal(18,2)) Payments,CAST(c.OpeningBalance+ISNULL((SELECT SUM(s2.GrandTotal-s2.PaidAmount) FROM Sales s2 WHERE s2.CustomerId=c.Id AND s2.Status='Completed'),0)-ISNULL((SELECT SUM(cp2.Amount) FROM CustomerPayments cp2 WHERE cp2.CustomerId=c.Id),0) AS decimal(18,2)) CurrentBalance FROM Customers c WHERE c.IsActive=1 AND (@q='' OR c.Name LIKE @like OR ISNULL(c.Phone,'') LIKE @like) ORDER BY c.Name";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "sales-return":sql=@"SELECT r.ReturnNo,r.ReturnDate,r.CustomerName,r.GrandTotal,r.Reason,p.Name,p.Barcode,l.Quantity,l.Rate,CAST(l.Quantity*l.Rate AS decimal(18,2)) Amount FROM SalesReturns r JOIN SalesReturnLines l ON l.ReturnId=r.Id JOIN Products p ON p.Id=l.ProductId WHERE r.ReturnDate>=@f AND r.ReturnDate<@e AND (@q='' OR r.ReturnNo LIKE @like OR ISNULL(r.CustomerName,'') LIKE @like OR p.Name LIKE @like) ORDER BY r.ReturnDate DESC";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "purchase":sql=@"SELECT p.Id,p.InvoiceNo,p.PurchaseDate,p.SupplierName,p.PaymentMode,p.SubTotal,p.Discount,p.Tax,p.GrandTotal,p.PaidAmount FROM Purchases p WHERE p.PurchaseDate>=@f AND p.PurchaseDate<@e AND (@q='' OR p.InvoiceNo LIKE @like OR p.SupplierName LIKE @like) AND (@sid IS NULL OR p.SupplierId=@sid) ORDER BY p.PurchaseDate DESC";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like),P("@sid",supplierId)};break;
                case "item-purchase":sql=@"SELECT p.PurchaseDate,p.InvoiceNo,p.SupplierName,pr.Name,pr.Barcode,pr.Category,pl.Quantity,pl.CostPrice,pl.TaxRate,CAST(pl.Quantity*pl.CostPrice AS decimal(18,2)) TaxableValue,pl.BatchId FROM PurchaseLines pl JOIN Purchases p ON p.Id=pl.PurchaseId JOIN Products pr ON pr.Id=pl.ProductId WHERE p.PurchaseDate>=@f AND p.PurchaseDate<@e AND (@q='' OR pr.Name LIKE @like OR ISNULL(pr.Barcode,'') LIKE @like OR p.SupplierName LIKE @like) AND (@sid IS NULL OR p.SupplierId=@sid) ORDER BY p.PurchaseDate DESC,pr.Name";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like),P("@sid",supplierId)};break;
                case "supplier-purchase":sql=@"SELECT p.SupplierName,COUNT(*) Bills,CAST(SUM(p.SubTotal) AS decimal(18,2)) SubTotal,CAST(SUM(p.Tax) AS decimal(18,2)) Tax,CAST(SUM(p.GrandTotal) AS decimal(18,2)) GrandTotal,CAST(SUM(p.PaidAmount) AS decimal(18,2)) Paid FROM Purchases p WHERE p.PurchaseDate>=@f AND p.PurchaseDate<@e AND (@sid IS NULL OR p.SupplierId=@sid) GROUP BY p.SupplierName ORDER BY GrandTotal DESC";ps=new[]{P("@f",f),P("@e",end),P("@sid",supplierId)};break;
                case "supplier-ledger":sql=@"SELECT s.Name,s.Phone,CAST(s.OpeningBalance AS decimal(18,2)) OpeningBalance,CAST(ISNULL((SELECT SUM(p.GrandTotal) FROM Purchases p WHERE p.SupplierId=s.Id AND p.PurchaseDate>=@f AND p.PurchaseDate<@e),0) AS decimal(18,2)) Purchases,CAST(ISNULL((SELECT SUM(sp.Amount) FROM SupplierPayments sp WHERE sp.SupplierId=s.Id AND sp.PaymentDate>=@f AND sp.PaymentDate<@e),0) AS decimal(18,2)) Payments,CAST(s.OpeningBalance+ISNULL((SELECT SUM(p2.GrandTotal-p2.PaidAmount) FROM Purchases p2 WHERE p2.SupplierId=s.Id),0)-ISNULL((SELECT SUM(sp2.Amount) FROM SupplierPayments sp2 WHERE sp2.SupplierId=s.Id),0) AS decimal(18,2)) CurrentBalance FROM Suppliers s WHERE s.IsActive=1 AND (@q='' OR s.Name LIKE @like OR ISNULL(s.Phone,'') LIKE @like) ORDER BY s.Name";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "purchase-return":sql=@"SELECT r.ReturnNo,r.ReturnDate,r.SupplierName,r.GrandTotal,r.Reason,p.Name,p.Barcode,l.Quantity,l.Rate,CAST(l.Quantity*l.Rate AS decimal(18,2)) Amount FROM PurchaseReturns r JOIN PurchaseReturnLines l ON l.ReturnId=r.Id JOIN Products p ON p.Id=l.ProductId WHERE r.ReturnDate>=@f AND r.ReturnDate<@e AND (@q='' OR r.ReturnNo LIKE @like OR ISNULL(r.SupplierName,'') LIKE @like OR p.Name LIKE @like) ORDER BY r.ReturnDate DESC";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "supplier-purchase-return":sql=@"SELECT r.SupplierName,COUNT(*) Returns,CAST(SUM(r.GrandTotal) AS decimal(18,2)) ReturnValue FROM PurchaseReturns r WHERE r.ReturnDate>=@f AND r.ReturnDate<@e GROUP BY r.SupplierName ORDER BY ReturnValue DESC";ps=new[]{P("@f",f),P("@e",end)};break;
                case "payment-register":sql=@"SELECT 'CUSTOMER' PartyType,c.Name Party,cp.PaymentDate,cp.Amount,cp.PaymentMode,cp.ReferenceNo,cp.Notes FROM CustomerPayments cp JOIN Customers c ON c.Id=cp.CustomerId WHERE cp.PaymentDate>=@f AND cp.PaymentDate<@e UNION ALL SELECT 'SUPPLIER',s.Name,sp.PaymentDate,sp.Amount,sp.PaymentMode,sp.ReferenceNo,sp.Notes FROM SupplierPayments sp JOIN Suppliers s ON s.Id=sp.SupplierId WHERE sp.PaymentDate>=@f AND sp.PaymentDate<@e ORDER BY PaymentDate DESC";ps=new[]{P("@f",f),P("@e",end)};break;
                case "gstr1":sql=@"SELECT s.InvoiceNo,s.BillDate,s.CustomerName,c.GstIn CustomerGstin,sl.TaxRate,CAST(sl.Quantity*sl.SalePrice-sl.Discount AS decimal(18,2)) TaxableValue,CAST((sl.Quantity*sl.SalePrice-sl.Discount)*sl.TaxRate/200 AS decimal(18,2)) CGST,CAST((sl.Quantity*sl.SalePrice-sl.Discount)*sl.TaxRate/200 AS decimal(18,2)) SGST,CAST((sl.Quantity*sl.SalePrice-sl.Discount)*sl.TaxRate/100 AS decimal(18,2)) TaxAmount,CAST((sl.Quantity*sl.SalePrice-sl.Discount)*(1+sl.TaxRate/100) AS decimal(18,2)) InvoiceLineValue FROM Sales s JOIN SaleLines sl ON sl.SaleId=s.Id JOIN Products p ON p.Id=sl.ProductId LEFT JOIN Customers c ON c.Id=s.CustomerId WHERE s.BillDate>=@f AND s.BillDate<@e AND s.Status='Completed' ORDER BY s.BillDate,s.InvoiceNo";ps=new[]{P("@f",f),P("@e",end)};break;
                case "hsn-summary":sql=@"SELECT p.Hsn,sl.TaxRate,CAST(SUM(sl.Quantity*sl.SalePrice-sl.Discount) AS decimal(18,2)) TaxableValue,CAST(SUM((sl.Quantity*sl.SalePrice-sl.Discount)*sl.TaxRate/100) AS decimal(18,2)) TaxAmount,SUM(sl.Quantity) Quantity FROM SaleLines sl JOIN Sales s ON s.Id=sl.SaleId JOIN Products p ON p.Id=sl.ProductId WHERE s.BillDate>=@f AND s.BillDate<@e AND s.Status='Completed' GROUP BY p.Hsn,sl.TaxRate ORDER BY p.Hsn,sl.TaxRate";ps=new[]{P("@f",f),P("@e",end)};break;
                case "tax-summary":sql=@"SELECT 'SALE' Source,sl.TaxRate,CAST(SUM(sl.Quantity*sl.SalePrice-sl.Discount) AS decimal(18,2)) TaxableValue,CAST(SUM((sl.Quantity*sl.SalePrice-sl.Discount)*sl.TaxRate/100) AS decimal(18,2)) TaxAmount FROM Sales s JOIN SaleLines sl ON sl.SaleId=s.Id WHERE s.BillDate>=@f AND s.BillDate<@e AND s.Status='Completed' GROUP BY sl.TaxRate UNION ALL SELECT 'PURCHASE',pl.TaxRate,CAST(SUM(pl.Quantity*pl.CostPrice) AS decimal(18,2)),CAST(SUM(pl.TaxAmount) AS decimal(18,2)) FROM Purchases p JOIN PurchaseLines pl ON pl.PurchaseId=p.Id WHERE p.PurchaseDate>=@f AND p.PurchaseDate<@e GROUP BY pl.TaxRate ORDER BY Source,TaxRate";ps=new[]{P("@f",f),P("@e",end)};break;
                case "expired":sql=@"SELECT p.Name,p.Barcode,p.Category,b.BatchNo,b.Quantity,b.CostPrice,b.Mrp,b.ExpiryDate,DATEDIFF(day,b.ExpiryDate,CAST(GETDATE() AS date)) DaysExpired,p.LocationCode,p.RackName FROM ProductBatches b JOIN Products p ON p.Id=b.ProductId WHERE b.Quantity>0 AND b.ExpiryDate<CAST(GETDATE() AS date) AND (@q='' OR p.Name LIKE @like OR ISNULL(p.Barcode,'') LIKE @like OR ISNULL(b.BatchNo,'') LIKE @like) ORDER BY b.ExpiryDate";ps=new[]{P("@q",term),P("@like",like)};break;
                case "close-expiry":sql=@"SELECT p.Name,p.Barcode,p.Category,b.BatchNo,b.Quantity,b.Mrp,b.ExpiryDate,DATEDIFF(day,CAST(GETDATE() AS date),b.ExpiryDate) DaysLeft,p.LocationCode,p.RackName FROM ProductBatches b JOIN Products p ON p.Id=b.ProductId WHERE b.Quantity>0 AND b.ExpiryDate>=CAST(GETDATE() AS date) AND b.ExpiryDate<DATEADD(day,@days,CAST(GETDATE() AS date)) AND (@q='' OR p.Name LIKE @like OR ISNULL(p.Barcode,'') LIKE @like) ORDER BY b.ExpiryDate";ps=new[]{P("@days",Math.Max(1,expiryDays)),P("@q",term),P("@like",like)};break;
                case "dead-stock":sql=@"SELECT p.Id,p.Name,p.Barcode,p.Category,p.LocationCode,p.RackName,CAST(SUM(b.Quantity) AS decimal(18,3)) Stock,CAST(SUM(b.Quantity*b.CostPrice) AS decimal(18,2)) StockValue,MAX(s.BillDate) LastSaleDate,DATEDIFF(day,ISNULL(MAX(s.BillDate),p.CreatedAt),GETDATE()) DaysSinceSale FROM Products p JOIN ProductBatches b ON b.ProductId=p.Id LEFT JOIN SaleLines sl ON sl.ProductId=p.Id LEFT JOIN Sales s ON s.Id=sl.SaleId AND s.Status='Completed' WHERE p.IsActive=1 AND b.Quantity>0 AND (@q='' OR p.Name LIKE @like OR ISNULL(p.Barcode,'') LIKE @like) GROUP BY p.Id,p.Name,p.Barcode,p.Category,p.LocationCode,p.RackName,p.CreatedAt HAVING MAX(s.BillDate) IS NULL OR MAX(s.BillDate)<DATEADD(day,-@deadDays,GETDATE()) ORDER BY DaysSinceSale DESC";ps=new[]{P("@deadDays",Math.Max(1,deadDays)),P("@q",term),P("@like",like)};break;
                case "audit":sql=@"SELECT CreatedAt,UserName,Action,Entity,EntityId,Details FROM AuditLogs WHERE CreatedAt>=@f AND CreatedAt<@e AND (@q='' OR ISNULL(UserName,'') LIKE @like OR Action LIKE @like OR ISNULL(Entity,'') LIKE @like OR ISNULL(Details,'') LIKE @like) ORDER BY CreatedAt DESC";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "expenses":sql=@"SELECT ExpenseDate,Category,Amount,PaymentMode,Notes FROM Expenses WHERE ExpenseDate>=@f AND ExpenseDate<@e AND (@q='' OR Category LIKE @like OR ISNULL(Notes,'') LIKE @like) ORDER BY ExpenseDate DESC";ps=new[]{P("@f",f),P("@e",end),P("@q",term),P("@like",like)};break;
                case "profit-loss":sql=@"SELECT CAST(ISNULL((SELECT SUM(GrandTotal) FROM Sales WHERE BillDate>=@f AND BillDate<@e AND Status='Completed'),0) AS decimal(18,2)) Sales,CAST(ISNULL((SELECT SUM(TotalCost) FROM Sales WHERE BillDate>=@f AND BillDate<@e AND Status='Completed'),0) AS decimal(18,2)) CostOfSales,CAST(ISNULL((SELECT SUM(GrandTotal) FROM SalesReturns WHERE ReturnDate>=@f AND ReturnDate<@e),0) AS decimal(18,2)) SalesReturns,CAST(ISNULL((SELECT SUM(Amount) FROM Expenses WHERE ExpenseDate>=@f AND ExpenseDate<@e),0) AS decimal(18,2)) Expenses";ps=new[]{P("@f",f),P("@e",end)};break;
                case "day-closing":sql=@"SELECT BusinessDate,OpeningCash,CashSales,CashIn,CashOut,ClosingCash,ClosedBy,ClosedAt,Notes FROM DayClosings WHERE BusinessDate>=CAST(@f AS date) AND BusinessDate<CAST(@e AS date) ORDER BY BusinessDate DESC";ps=new[]{P("@f",f),P("@e",end)};break;
                default:return Results.BadRequest(new{message="Unknown report type"});
            }
            return Results.Ok(await db.QueryAsync(sql,ps));
        });
    }
    public record TaxRequest(string TaxName,decimal Rate);
}
