using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Net;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.Data.SqlClient;
using NPOI.SS.UserModel;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;
using SuvidhaPOS.Premium;
using SuvidhaPOS.Premium.Data;
using Row = SuvidhaPOS.Premium.PurchaseImportModules.PurchaseImportRow;

static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
static async Task<List<Row>> Parse(byte[] bytes,string name){
 using var stream=new MemoryStream(bytes);
 var file=new FormFile(stream,0,bytes.Length,"file",name);
 var method=typeof(PurchaseImportModules).GetMethod("Parse",BindingFlags.Static|BindingFlags.NonPublic)!;
 var task=(Task)method.Invoke(null,new object[]{file})!;await task;
 var result=task.GetType().GetProperty("Result")!.GetValue(task)!;
 Check(result.GetType().GetProperty("Error")!.GetValue(result)==null,"Synthetic fixture should parse");
 return (List<Row>)result.GetType().GetProperty("Rows")!.GetValue(result)!;
}
var headers=new[]{"Date","Vch/Bill No","Particulars","Group","Item Details","TAX RATE","HSN CODE","BCN","MRP","Disc.","Qty.","Unit","Price","Amount"};
foreach(var xls in new[]{true,false}){
 IWorkbook book=xls?new HSSFWorkbook():new XSSFWorkbook();var sheet=book.CreateSheet("Synthetic");
 var header=sheet.CreateRow(0);for(int i=0;i<headers.Length;i++)header.CreateCell(i).SetCellValue(headers[i]);
 var first=sheet.CreateRow(1);var values=new[]{"25/08/2026","SYNTH-001","Synthetic Supplier","General"," Demo  Widget ","Exempt","1234","","12","10%","2","PCS","₹10","20"};
 for(int i=0;i<values.Length;i++)first.CreateCell(i).SetCellValue(values[i]);first.GetCell(7).SetCellValue(8901234567890d);
 var second=sheet.CreateRow(2);second.CreateCell(4).SetCellValue("demo widget");second.CreateCell(8).SetCellValue(14);second.CreateCell(9).SetCellValue(0.05);second.GetCell(9).CellStyle=book.CreateCellStyle();second.GetCell(9).CellStyle.DataFormat=book.CreateDataFormat().GetFormat("0%");second.CreateCell(10).SetCellValue(3);second.CreateCell(11).SetCellValue("PCS");second.CreateCell(12).SetCellValue(9);
 using var ms=new MemoryStream();book.Write(ms,true);var rows=await Parse(ms.ToArray(),xls?"synthetic.xls":"synthetic.xlsx");
 Check(rows.Count==2,"Only two source item rows");Check(rows[0].Barcode=="8901234567890","Numeric Excel barcode must retain plain digits");
 Check(rows[0].Discount==10&&rows[1].Discount==5,"Percent text and percentage cells retain percentage semantics");
 Check(rows.All(r=>r.PurchaseDate==new DateTime(2026,8,25)),"Day-first dates fill down");
 Check(rows.All(r=>r.SupplierName=="Synthetic Supplier"),"Particulars supplier metadata must fill down when Item Details exists");
 Check(rows.All(r=>r.InvoiceNo=="SYNTH-001"),"Invoice metadata fills down");Check(rows[0].GstRate==0,"Exempt means zero GST");
}
var csv=string.Join(',',headers)+"\n25/08/2026,SYNTH-002,Synthetic Supplier,General,CSV Widget,Exempt,1234,00123,14,10%,2,PCS,10,20\n,,,,CSV Widget,Exempt,,,14,5,3,PCS,9,27\n,,,,Bad Quantity,Exempt,,,14,5,abc,PCS,9,27";
var csvRows=await Parse(Encoding.UTF8.GetBytes(csv),"synthetic.csv");
Check(csvRows[1].PurchaseDate==new DateTime(2026,8,25)&&csvRows[1].InvoiceNo=="SYNTH-002","CSV metadata uses same fill-down as Excel");
var errors=typeof(Row).GetProperty("Errors")?.GetValue(csvRows[2]) as System.Collections.IEnumerable;
Check(errors!=null&&errors.Cast<object>().Any(),"Malformed quantity must create a row error, never silently become one");
var badTax=await Parse(Encoding.UTF8.GetBytes(string.Join(',',headers)+"\n25/08/2026,SYNTH-TAX,Synthetic Supplier,General,Invalid GST,GST 18+5%,1234,00123,14,5,2,PCS,10,20"),"bad-tax.csv");
 Check(badTax[0].GstRate<0||((typeof(Row).GetProperty("Errors")?.GetValue(badTax[0]) as System.Collections.IEnumerable)?.Cast<object>().Any()??false),"Multiple tax numbers must not be guessed or merged");
 var totalRows=await Parse(Encoding.UTF8.GetBytes(string.Join(',',headers)+"\n25/08/2026,SYNTH-TOTAL,Synthetic Supplier,General,Good Widget,Exempt,1234,00123,14,5,2,PCS,10,20\n,,,,Grand Total,,,,,,2,,,20"),"total.csv");
 Check(totalRows.Count==1,"Grand total row is excluded from candidates");
 var incomplete=await Parse(Encoding.UTF8.GetBytes(string.Join(',',headers)+"\n25/08/2026,SYNTH-MISSING,Synthetic Supplier,,,,,,14,,,,10,20"),"incomplete.csv");
 Check(incomplete.Count==1&&incomplete[0].Errors.Count>0,"Rows with amounts but missing identity/quantity remain visible for correction");
 Console.WriteLine("PASS: XLS/XLSX/CSV typed parser, plain barcode, percentage, Exempt, day-first dates, metadata fill-down, invalid numeric errors");
var tooPrecise=new Row{ItemName="Fractional",InvoiceNo="FRACTION",SupplierName="Supplier",PurchaseDate=new DateTime(2026,8,25),Qty=0.0004m,PurchaseRate=1000};
PurchaseImportRules.ValidateValues(tooPrecise);Check(tooPrecise.Errors.Any(e=>e.Contains("decimal places")),"Quantity smaller than storage precision must not silently vanish");
var unitDefinitions=new List<PurchaseImportRules.UnitDefinition>{new("PCS","PCS"),new("BOX","BOX")};
Row Pure(string name,decimal qty=1,decimal cost=10,decimal mrp=14,decimal discount=10,string barcode="PURE")=>new(){RowNo=1,ItemName=name,Qty=qty,PurchaseRate=cost,Mrp=mrp,Discount=discount,Barcode=barcode,Unit="PCS",InvoiceNo="PURE-001",SupplierName="Synthetic Supplier",PurchaseDate=new DateTime(2026,8,25)};
PurchaseImportModules.PurchaseImportCommitRequest PureRequest(params Row[] rows)=>new(null,null,null,null,null,0,0,rows.ToList());
var grouping=PurchaseImportRules.Validate(PureRequest(Pure(" Widget ",2,10,12,5),Pure("widget",3,9,14,10)),new(),unitDefinitions);
Check(grouping.Groups.Count==1&&grouping.Groups[0].PurchasePrice==9.5m&&grouping.Groups[0].Mrp==14&&grouping.Groups[0].Discount==10&&grouping.Groups[0].SalePrice==12.6m&&grouping.Groups[0].Quantity==5,"Pure grouping uses arithmetic mean/max rates and original quantities");
Check(grouping.Rows.Select(r=>r.PurchaseRate).SequenceEqual(new[]{10m,9m}),"Grouping never rewrites original purchase rates");
var masterFixture=new List<PurchaseImportRules.Master>{new(41," Widget ","OWNED",true,"PCS","PCS",null,"BOX",1,10)};
var forged=Pure("widget",barcode:"DIFFERENT");forged.ProductId=999;forged.NewItem=true;forged.Errors=new(){"client error"};
var matches=PurchaseImportRules.Validate(PureRequest(forged,Pure("Another name",barcode:"OWNED")),masterFixture,unitDefinitions);
Check(matches.Rows[0].ProductId==41&&!matches.Rows[0].NewItem&&matches.Rows[0].Errors.Count==0,"Never trust client product id, new-item flag or errors");
Check(matches.Rows[1].NewItem&&matches.Rows[1].Barcode=="OWNED"&&matches.Rows[1].EffectiveBarcode==null&&matches.Rows[1].Status=="BARCODE_CLEARED","Barcode collision clears only effective new barcode");
var nullBarcode=PurchaseImportRules.Validate(PureRequest(Pure("widget",barcode:"EXTERNAL")),new(){masterFixture[0] with{Barcode=null}},unitDefinitions);
Check(nullBarcode.Rows[0].EffectiveBarcode==null,"Matched master with a blank barcode stays blank");
var ambiguous=PurchaseImportRules.Validate(PureRequest(Pure("widget")),new(){masterFixture[0],masterFixture[0] with{Id=42,Name="WIDGET"}},unitDefinitions);
Check(ambiguous.Rows[0].Errors.Any(e=>e.Contains("Multiple existing")),"Ambiguous historical duplicate names block matching");
var inactive=PurchaseImportRules.Validate(PureRequest(Pure("widget")),new(){masterFixture[0] with{Active=false}},unitDefinitions);
Check(inactive.Rows[0].Errors.Any(e=>e.Contains("inactive")),"Inactive match cannot silently become a new master");
var pack=Pure("widget",2);pack.Unit="BOX";var converted=PurchaseImportRules.Validate(PureRequest(pack),masterFixture,unitDefinitions);
Check(converted.Rows[0].BaseFactor==10&&converted.Groups[0].Quantity==20,"Existing pack converts stock using preserved master factor");
var differentPack=Pure("widget");differentPack.Unit="BOX";
Check(PurchaseImportRules.Validate(PureRequest(Pure("widget"),differentPack),new(),unitDefinitions).Rows[1].Errors.Any(),"New same-name group with incompatible units blocks");
Check(PurchaseImportRules.Validate(PureRequest(Pure("No expiry")),new(),unitDefinitions,false,true).Rows[0].Errors.Any(e=>e.Contains("Expiry")),"Required expiry blocks missing date");
Check(PurchaseImportRules.Tax(236,18,"INCLUSIVE")==36&&PurchaseImportRules.Tax(200,18,"EXCLUSIVE")==36,"Tax modes reconcile entered amounts");
Check(PurchaseImportParser.Number("GST 18+5%",true)<0&&PurchaseImportParser.Number("Rs. 1,234.50")==1234.50m&&PurchaseImportParser.Number(".5")==0.5m,"Decorations parse without merging numbers");
Console.WriteLine("PASS: pure aggregation, name matching, collisions, protected identity, units, expiry and inclusive tax");

if(args.Length==0)return;
var cs=new SqlConnectionStringBuilder(args[0]);var database="RetailChecks_"+Guid.NewGuid().ToString("N");cs.InitialCatalog="master";
using var master=new SqlConnection(cs.ConnectionString);await master.OpenAsync();await new SqlCommand("CREATE DATABASE ["+database+"]",master).ExecuteNonQueryAsync();cs.InitialCatalog=database;
WebApplication? server=null;
try{
 using var connection=new SqlConnection(cs.ConnectionString);await connection.OpenAsync();
 foreach(var script in new[]{"schema.sql","specialized-schema.sql","print-schema.sql","completion-schema.sql","btc-settlement-schema.sql","held-bills-schema.sql","retail-expansion-schema.sql","retail-purchase-schema.sql"}){
  var path="src/SuvidhaPOS-Premium/Database/"+script;if(!File.Exists(path))continue;
  foreach(var batch in System.Text.RegularExpressions.Regex.Split(File.ReadAllText(path),@"^\s*GO\s*$",System.Text.RegularExpressions.RegexOptions.Multiline|System.Text.RegularExpressions.RegexOptions.IgnoreCase))if(!string.IsNullOrWhiteSpace(batch)&&!batch.Contains("CREATE DATABASE [SuvidhaPOS]")&&!batch.TrimStart().StartsWith("USE [SuvidhaPOS]",StringComparison.OrdinalIgnoreCase))await new SqlCommand(batch,connection).ExecuteNonQueryAsync();
 }
 await new SqlCommand("IF NOT EXISTS(SELECT 1 FROM UnitMaster WHERE UnitName='PCS') INSERT UnitMaster(UnitName,UnitCode,IsActive) VALUES('PCS','PCS',1)",connection).ExecuteNonQueryAsync();
 var builder=WebApplication.CreateBuilder();builder.Configuration["ConnectionStrings:DefaultConnection"]=cs.ConnectionString;builder.Services.AddSingleton<Db>();server=builder.Build();server.Urls.Add("http://127.0.0.1:0");PurchaseImportModules.Map(server);RetailExpansionModules.Map(server);InventoryMasterModules.Map(server);RetailThermalReportModules.Map(server);
 var productType=typeof(RetailItemRules).Assembly.GetType("ProductRequest")!;
 var purchaseType=typeof(RetailItemRules).Assembly.GetType("PurchaseRequest")!;
 var jsonOptions=new JsonSerializerOptions{PropertyNameCaseInsensitive=true};
 server.MapPost("/checks/product/{id:int}",(Db db,int id,JsonElement requestJson)=>(Task<IResult>)typeof(RetailItemRules).GetMethod("Save",BindingFlags.Static|BindingFlags.NonPublic)!.Invoke(null,new object?[]{db,id==0?null:(int?)id,JsonSerializer.Deserialize(requestJson.GetRawText(),productType,jsonOptions)})!);
 server.MapPost("/checks/purchase",(Db db,JsonElement requestJson)=>(Task<IResult>)typeof(RetailItemRules).Assembly.GetType("SuvidhaPOS.Premium.ManualPurchaseService")!.GetMethod("Commit",BindingFlags.Static|BindingFlags.NonPublic)!.Invoke(null,new object?[]{db,JsonSerializer.Deserialize(requestJson.GetRawText(),purchaseType,jsonOptions),"checks"})!);
 server.MapPost("/checks/normal-import",(Db db,HttpContext context,NormalImportRequest input)=>(Task<IResult>)typeof(PremiumCompletionModules).GetMethod("CommitNormal",BindingFlags.Static|BindingFlags.NonPublic)!.Invoke(null,new object?[]{db,context,input})!);
 await server.StartAsync();
 using var http=new HttpClient{BaseAddress=new Uri(server.Urls.Single())};
 Row R(string name,decimal qty,decimal cost,decimal mrp,decimal discount,string barcode="SYNTH-BC")=>new(){RowNo=1,ItemName=name,Qty=qty,PurchaseRate=cost,Mrp=mrp,Discount=discount,Barcode=barcode,Unit="PCS",InvoiceNo="SYNTH-003",SupplierName="Synthetic Supplier",PurchaseDate=new DateTime(2026,8,25),GstRate=0};
 await new SqlCommand("INSERT Suppliers(Name) VALUES('Synthetic Supplier')",connection).ExecuteNonQueryAsync();
 var rows=new[]{R("Demo  Widget",2,10,12,5),R(" demo widget ",3,9,14,10)};
 var requestId=Guid.NewGuid().ToString();var body=new{rows,requestId};
 async Task<JsonElement> Post(object payload){var response=await http.PostAsJsonAsync("/api/purchase-import/commit",payload);var content=await response.Content.ReadAsStringAsync();Check(response.IsSuccessStatusCode,"Commit: "+content);return JsonDocument.Parse(content).RootElement.Clone();}
 var committed=await Post(body);Check(committed.GetProperty("newItems").GetInt32()==1,"Same normalized names create one master");
 using(var command=new SqlCommand("SELECT PurchasePrice,Mrp,Dis_Rate,SalePrice,TaxMode FROM Products",connection))using(var rd=await command.ExecuteReaderAsync()){Check(await rd.ReadAsync(),"New master exists");Check(rd.GetDecimal(0)==9.5m&&rd.GetDecimal(1)==14&&rd.GetDecimal(2)==10&&rd.GetDecimal(3)==12.6m,"New master mean cost/max MRP/max discount");Check(rd.GetString(4)=="INCLUSIVE","New master defaults inclusive");Check(!await rd.ReadAsync(),"No duplicate master");}
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM Purchases p JOIN Suppliers s ON s.Id=p.SupplierId WHERE s.Name='Synthetic Supplier'",connection).ExecuteScalarAsync())==1,"Imported credit purchase is linked to the supplier ledger");
 Check(Convert.ToDecimal(await new SqlCommand("SELECT SUM(Quantity) FROM ProductBatches",connection).ExecuteScalarAsync())==5,"Stock equals original quantities");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM ProductBatches WHERE (Quantity=2 AND CostPrice=10) OR (Quantity=3 AND CostPrice=9)",connection).ExecuteScalarAsync())==2,"Original separate batch costs remain unchanged");
 var replay=await Post(body);Check(replay.GetProperty("alreadyImported").GetBoolean(),"Identical request retry is idempotent");
 rows[0].Qty=9;var changed=await http.PostAsJsonAsync("/api/purchase-import/commit",body);Check(changed.StatusCode==HttpStatusCode.BadRequest,"Changed payload under same key rejected");rows[0].Qty=2;
 var duplicate=await http.PostAsJsonAsync("/api/purchase-import/commit",new{rows,requestId=Guid.NewGuid().ToString()});Check(duplicate.StatusCode==HttpStatusCode.BadRequest,"Duplicate invoice across requests rejected");
 var collision=R("Other Widget",1,8,16,20);collision.InvoiceNo="SYNTH-004";await Post(new{rows=new[]{collision},requestId=Guid.NewGuid().ToString()});
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM Products WHERE Name='Other Widget' AND Barcode IS NULL",connection).ExecuteScalarAsync())==1,"Different name collision creates separate master with null barcode");
 var existing=R("demo widget",1,99,999,99,"OTHER-CODE");existing.InvoiceNo="SYNTH-005";await Post(new{rows=new[]{existing},requestId=Guid.NewGuid().ToString()});
 Check(Convert.ToDecimal(await new SqlCommand("SELECT PurchasePrice FROM Products WHERE Barcode='SYNTH-BC'",connection).ExecuteScalarAsync())==9.5m,"Existing master cost preserved");
 var invalid=R("Must Roll Back",1,5,10,0,"ROLLBACK");invalid.InvoiceNo="SYNTH-006";var bad=R("Bad Later",-1,5,10,0,"BAD");bad.InvoiceNo="SYNTH-006";
 var failure=await http.PostAsJsonAsync("/api/purchase-import/commit",new{rows=new[]{invalid,bad},requestId=Guid.NewGuid().ToString()});Check(failure.StatusCode==HttpStatusCode.BadRequest,"Invalid later row rejects whole upload");Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM Products WHERE Barcode='ROLLBACK'",connection).ExecuteScalarAsync())==0,"Failed upload leaves no earlier product");
 var incl=R("Inclusive Widget",2,118,150,10,"INCLUSIVE");incl.InvoiceNo="SYNTH-007";incl.GstRate=18;
 var inclResult=await Post(new{rows=new[]{incl},requestId=Guid.NewGuid().ToString()});Check(inclResult.GetProperty("total").GetDecimal()==236,"Inclusive purchase tax is extracted, never added twice");
 Check(Convert.ToDecimal(await new SqlCommand("SELECT Tax FROM Purchases WHERE InvoiceNo='SYNTH-007'",connection).ExecuteScalarAsync())==36,"Inclusive invoice GST reconciles");
 var concurrentRows=new[]{R("Concurrent Widget",1,10,12,0,"CONCURRENT")};concurrentRows[0].InvoiceNo="SYNTH-008";
 var concurrentResults=await Task.WhenAll(http.PostAsJsonAsync("/api/purchase-import/commit",new{rows=concurrentRows,requestId=Guid.NewGuid().ToString()}),http.PostAsJsonAsync("/api/purchase-import/commit",new{rows=concurrentRows,requestId=Guid.NewGuid().ToString()}));
 Check(concurrentResults.Count(r=>r.IsSuccessStatusCode)==1&&concurrentResults.Count(r=>r.StatusCode==HttpStatusCode.BadRequest)==1,"Concurrent duplicate invoice posts exactly once");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM Products WHERE Name='Concurrent Widget'",connection).ExecuteScalarAsync())==1,"Concurrent normalized names allocate one SQL identity");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*)-COUNT(DISTINCT Id) FROM Products",connection).ExecuteScalarAsync())==0,"Item codes remain unique SQL identities");
 var fileRow=R("Source protected",1,5,10,0,"FILE-CHECK");fileRow.InvoiceNo="FILE-001";
 var sourceToken=new string('A',64);await Post(new{rows=new[]{fileRow},requestId=Guid.NewGuid().ToString(),sourceToken});fileRow.InvoiceNo="FILE-002";
 var sameFile=await http.PostAsJsonAsync("/api/purchase-import/commit",new{rows=new[]{fileRow},requestId=Guid.NewGuid().ToString(),sourceToken});Check(sameFile.StatusCode==HttpStatusCode.BadRequest,"Same source file cannot post again after metadata changes");
 var supplierRow=R("New supplier product",1,5,10,0,"NEW-SUP");supplierRow.InvoiceNo="NEW-SUP-001";supplierRow.SupplierName="New Synthetic Supplier";await Post(new{rows=new[]{supplierRow},requestId=Guid.NewGuid().ToString()});
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM Purchases p JOIN Suppliers s ON s.Id=p.SupplierId WHERE s.Name='New Synthetic Supplier'",connection).ExecuteScalarAsync())==1,"New supplier is created and linked in the same transaction");
 var tokenRow=R("Preview drift",1,10,20,5,"DRIFT");tokenRow.InvoiceNo="SYNTH-009";
 var previewResponse=await http.PostAsJsonAsync("/api/purchase-import/validate",new{rows=new[]{tokenRow},requestId=Guid.NewGuid().ToString()});Check(previewResponse.IsSuccessStatusCode,"JSON validation returns preview");
 var previewJson=JsonDocument.Parse(await previewResponse.Content.ReadAsStringAsync()).RootElement.Clone();
 await new SqlCommand("INSERT Products(Name,Barcode,Unit) VALUES('Preview drift','DRIFT','PCS')",connection).ExecuteNonQueryAsync();
 var stale=await http.PostAsJsonAsync("/api/purchase-import/commit",new{rows=new[]{tokenRow},requestId=previewJson.GetProperty("requestId").GetString(),previewToken=previewJson.GetProperty("previewToken").GetString()});Check(stale.StatusCode==HttpStatusCode.BadRequest,"Changed matching after preview requires revalidation");
 var protectedId=Convert.ToInt32(await new SqlCommand("SELECT Id FROM Products WHERE Barcode='SYNTH-BC'",connection).ExecuteScalarAsync());
 await new SqlCommand("UPDATE Products SET SalePrice=11.37,TaxMode='EXCLUSIVE',Category='Historic',Hsn='KEEP' WHERE Id="+protectedId,connection).ExecuteNonQueryAsync();
 var productEdit=new{name="Demo Widget",barcode="SYNTH-BC",unit="PCS",category="Historic",hsn="KEEP",gstRate=0,mrp=14,purchasePrice=9.5m,salePrice=999,locationCode="A1"};
 var edit=await http.PostAsJsonAsync("/checks/product/"+protectedId,productEdit);Check(edit.IsSuccessStatusCode,"Unrelated product edit succeeds");
 Check(Convert.ToDecimal(await new SqlCommand("SELECT SalePrice FROM Products WHERE Id="+protectedId,connection).ExecuteScalarAsync())==11.37m,"Omitted discount preserves historic explicit sale price");
 Check((await new SqlCommand("SELECT TaxMode FROM Products WHERE Id="+protectedId,connection).ExecuteScalarAsync())?.ToString()=="EXCLUSIVE","Omitted edit tax mode preserves historic exclusive value");
 var missingBill=await http.PostAsJsonAsync("/checks/purchase",new{invoiceNo="",supplierName="Synthetic Supplier",lines=new[]{new{productId=protectedId,qty=1,cost=10,mrp=14,salePrice=14,taxRate=0}}});Check(missingBill.StatusCode==HttpStatusCode.BadRequest,"Manual purchase without Bill No is rejected server-side");
 var manualRequest=new{invoiceNo="MANUAL-001",supplierName="Synthetic Supplier",purchaseDate="2026-08-25",requestId=Guid.NewGuid().ToString(),lines=new[]{new{productId=protectedId,qty=2,cost=118,mrp=150,salePrice=1,taxRate=18,discountPer=10}}};
 var manual=await http.PostAsJsonAsync("/checks/purchase",manualRequest);Check(manual.IsSuccessStatusCode,"Ordinary retail purchase accepts missing expiry");
 Check(JsonDocument.Parse(await manual.Content.ReadAsStringAsync()).RootElement.GetProperty("total").GetDecimal()==236,"Manual purchase defaults inclusive despite historic exclusive master");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM ProductBatches b JOIN PurchaseLines l ON l.BatchId=b.Id JOIN Purchases p ON p.Id=l.PurchaseId WHERE p.InvoiceNo='MANUAL-001' AND b.SellingPrice=135 AND b.Dis_Rate=10 AND b.TaxMode='INCLUSIVE' AND l.Dis_Rate=10 AND l.TaxMode='INCLUSIVE' AND b.ExpiryDate='9999-12-31'",connection).ExecuteScalarAsync())==1,"Manual batch carries new discount/rate/tax and internal no-expiry sentinel");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM Products WHERE Id="+protectedId+" AND Mrp=150 AND SalePrice=135 AND Dis_Rate=10",connection).ExecuteScalarAsync())==1,"Explicit manual purchase discount updates master MRP, discount and sale price");
 var manualReplay=await http.PostAsJsonAsync("/checks/purchase",manualRequest);Check(JsonDocument.Parse(await manualReplay.Content.ReadAsStringAsync()).RootElement.GetProperty("alreadyImported").GetBoolean(),"Manual identical retry posts once");
 var badBase=await http.PostAsJsonAsync("/checks/product/"+protectedId,new{name="Demo Widget",barcode="SYNTH-BC",unit="BOX",mrp=14,purchasePrice=9.5m,salePrice=11.37m});Check(badBase.StatusCode==HttpStatusCode.BadRequest,"Base unit cannot change with stock/history");
 var invalidAtomic=await http.PostAsJsonAsync("/checks/product/0",new{name="Atomic rollback",unit="PCS",mrp=20,purchasePrice=10,salePrice=18,discountPer=10,uom=new{baseUnit="PCS",packUnit="INVALID",conversionFactor=1,innerConversionFactor=1,packInnerFactor=1}});Check(invalidAtomic.StatusCode==HttpStatusCode.BadRequest,"Invalid UOM rejects whole product save");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM Products WHERE Name='Atomic rollback'",connection).ExecuteScalarAsync())==0,"Atomic save failure leaves no product");
 var customUnit=await http.PostAsJsonAsync("/checks/product/0",new{name="Custom pack rates",unit="PCS",mrp=100,purchasePrice=10,salePrice=90,discountPer=10,uom=new{baseUnit="PCS",packUnit="BOX",conversionFactor=10,innerConversionFactor=1,packInnerFactor=10,packPurchaseRate=85,packMrp=250,packSalePrice=197,looseSalePrice=90,allowLoose=true}});
 Check(customUnit.IsSuccessStatusCode,"Custom UOM product saves atomically: "+await customUnit.Content.ReadAsStringAsync());
 var customId=JsonDocument.Parse(await customUnit.Content.ReadAsStringAsync()).RootElement.GetProperty("id").GetInt32();
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM ProductUoms WHERE ProductId="+customId+" AND PackPurchaseRate=85 AND PackMrp=250 AND PackSalePrice=197",connection).ExecuteScalarAsync())==1,"Explicit UOM rates survive item discount save");
 var customDiscount=await http.PostAsJsonAsync("/api/retail/item-rates/apply",new{rows=new[]{new{productId=customId,discountPer=10}}});Check(customDiscount.IsSuccessStatusCode,"Discount-only update succeeds");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM ProductUoms WHERE ProductId="+customId+" AND PackPurchaseRate=85 AND PackMrp=250 AND PackSalePrice=225",connection).ExecuteScalarAsync())==1,"Discount-only update uses existing pack MRP and preserves custom purchase/MRP");
 var packDiscount=await http.PostAsJsonAsync("/checks/purchase",new{invoiceNo="PACK-DISCOUNT",supplierName="Synthetic Supplier",requestId=Guid.NewGuid().ToString(),lines=new[]{new{productId=customId,qty=10,cost=8.5m,mrp=9.9m,mrpPerPurchasedUnit=99,salePrice=9.207m,discountPer=7,taxRate=0,unitPurchased="BOX",purchasedQty=1,ratePerPurchasedUnit=85}}});Check(packDiscount.IsSuccessStatusCode,"Purchased-unit discount posts successfully");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM PurchaseLines l JOIN Purchases p ON p.Id=l.PurchaseId WHERE p.InvoiceNo='PACK-DISCOUNT' AND l.SalePrice=9.207",connection).ExecuteScalarAsync())==1,"Discount rounds the purchased-unit MRP before base conversion");
 var fractionalCost=await http.PostAsJsonAsync("/checks/purchase",new{invoiceNo="FRACTIONAL-COST",supplierName="Synthetic Supplier",requestId=Guid.NewGuid().ToString(),lines=new[]{new{productId=customId,qty=10,cost=0.001m,mrp=1,salePrice=1,taxRate=0,unitPurchased="BOX",purchasedQty=1,ratePerPurchasedUnit=0.01m}}});Check(fractionalCost.IsSuccessStatusCode,"Sub-paise base cost posts without losing pack cost");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM PurchaseLines l JOIN Purchases p ON p.Id=l.PurchaseId WHERE p.InvoiceNo='FRACTIONAL-COST' AND l.Quantity=10 AND l.CostPrice=0.001",connection).ExecuteScalarAsync())==1,"Base-unit cost retains six-decimal storage precision");
 var normalProtected=await http.PostAsJsonAsync("/checks/normal-import",new{rows=new[]{new{name="Demo Widget",barcode="SYNTH-BC",resolution="UPDATE",unit="PCS",mrp=999,purchasePrice=999,salePrice=999,gstMode="INCLUSIVE"}}});Check(normalProtected.IsSuccessStatusCode,"Protected normal match returns a report");
 Check(JsonDocument.Parse(await normalProtected.Content.ReadAsStringAsync()).RootElement.GetProperty("matchesSkipped").GetInt32()==1,"Normal import reports protected matches even with UPDATE resolution");
 Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM Products WHERE Id="+protectedId+" AND Mrp=150 AND SalePrice=135 AND Dis_Rate=10",connection).ExecuteScalarAsync())==1,"Protected normal import does not overwrite the purchase-updated master");
  var inventoryId=Convert.ToInt32(await new SqlCommand("INSERT Products(Name,Unit,PurchasePrice,SalePrice,Mrp,IsActive) OUTPUT INSERTED.Id VALUES('Inventory Widget','PCS',10,15,20,1)",connection).ExecuteScalarAsync());
  var inventoryBatch=Convert.ToInt32(await new SqlCommand("INSERT ProductBatches(ProductId,BatchNo,Quantity,CostPrice,SellingPrice,Mrp,ExpiryDate) OUTPUT INSERTED.Id VALUES("+inventoryId+",'INV-BASE',10,10,15,20,'2030-12-31')",connection).ExecuteScalarAsync());
  await new SqlCommand("INSERT StockLedger(ProductId,BatchId,MovementType,Quantity,ReferenceType,Notes) VALUES("+inventoryId+","+inventoryBatch+",'OPENING',10,'OPENING','inventory check')",connection).ExecuteNonQueryAsync();
  var damage=await http.PostAsJsonAsync("/api/inventory/damage",new{productId=inventoryId,quantity=2,reason="Damaged",notes="SQL check"});Check(damage.IsSuccessStatusCode,"Inventory damage posts transactionally: "+await damage.Content.ReadAsStringAsync());
  Check(Convert.ToDecimal(await new SqlCommand("SELECT Quantity FROM ProductBatches WHERE Id="+inventoryBatch,connection).ExecuteScalarAsync())==8,"Damage deducts source batch");
  Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM StockLedger WHERE ProductId="+inventoryId+" AND MovementType='DAMAGE' AND Quantity=-2",connection).ExecuteScalarAsync())==1,"Damage ledger movement exists");
  var receive=await http.PostAsJsonAsync("/api/inventory/receive",new{productId=inventoryId,quantity=3,batchNo="INV-REC",expiryDate="2031-12-31",costPrice=11,salePrice=16,mrp=21,sourceName="Branch B",referenceNo="REF-001",notes="SQL check"});Check(receive.IsSuccessStatusCode,"Inventory receive posts transactionally: "+await receive.Content.ReadAsStringAsync());
  Check(Convert.ToDecimal(await new SqlCommand("SELECT SUM(Quantity) FROM ProductBatches WHERE ProductId="+inventoryId,connection).ExecuteScalarAsync())==11,"Receive increases stock");
  var transfer=await http.PostAsJsonAsync("/api/inventory/transfer",new{toOutlet="Branch B",notes="SQL check",lines=new[]{new{productId=inventoryId,quantity=4}}});Check(transfer.IsSuccessStatusCode,"Inventory transfer posts transactionally: "+await transfer.Content.ReadAsStringAsync());
  Check(Convert.ToDecimal(await new SqlCommand("SELECT SUM(Quantity) FROM ProductBatches WHERE ProductId="+inventoryId,connection).ExecuteScalarAsync())==7,"Transfer deducts source stock");
  Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM StockTransfers t JOIN StockTransferLines l ON l.TransferId=t.Id WHERE t.ToOutlet='Branch B' AND t.Status='IN_TRANSIT' AND l.ProductId="+inventoryId+" AND l.Quantity=4",connection).ExecuteScalarAsync())==1,"Transfer document records destination and quantity");
  Check(Convert.ToInt32(await new SqlCommand("SELECT COUNT(*) FROM StockLedger WHERE ProductId="+inventoryId+" AND MovementType='STOCK_TRANSFER_OUT' AND Quantity<0",connection).ExecuteScalarAsync())>=1,"Transfer ledger movement exists");
  var dateWise=await http.GetAsync("/api/inventory/stock-date-wise?from=2020-01-01&to=2035-12-31&q=Inventory");Check(dateWise.IsSuccessStatusCode,"Date-wise stock endpoint reads ledger movements");
  Console.WriteLine("PASS: Inventory damage, receive, transfer and date-wise stock SQL transactions");
  foreach(var type in new[]{"account-report","cashier-report","payment-mode-report","expense-report","day-close-report","audit-trail-report"})
  {
   var report=await http.GetAsync("/api/reports/thermal/"+type+"?from=2020-01-01&to=2035-12-31&cashier=&q=");
   Check(report.IsSuccessStatusCode,"80mm thermal report endpoint executes on SQL Server: "+type+" :: "+await report.Content.ReadAsStringAsync());
  }
  Console.WriteLine("PASS: six 80mm account/closing report endpoints execute on isolated SQL Server");
 var rateZero=await http.PostAsJsonAsync("/api/retail/item-rates/apply",new{rows=new[]{new{productId=protectedId,discountPer=0}}});Check(rateZero.IsSuccessStatusCode,"Explicit zero discount is a valid rate update");
 Check(Convert.ToDecimal(await new SqlCommand("SELECT SalePrice FROM Products WHERE Id="+protectedId,connection).ExecuteScalarAsync())==150,"Explicit zero discount resets selling price to current purchase-updated MRP");
 var invalidRate=await http.PostAsJsonAsync("/api/retail/item-rates/apply",new{rows=new[]{new{productId=protectedId,discountPer=101}}});Check(invalidRate.StatusCode==HttpStatusCode.BadRequest,"Invalid discount rejects rate update");
 await new SqlCommand("UPDATE OutletMaster SET RequireExpiry=1",connection).ExecuteNonQueryAsync();
 var expiryRequired=await http.PostAsJsonAsync("/checks/purchase",new{invoiceNo="MANUAL-002",supplierName="Synthetic Supplier",lines=new[]{new{productId=protectedId,qty=1,cost=10,mrp=14,salePrice=14,taxRate=0}}});Check(expiryRequired.StatusCode==HttpStatusCode.BadRequest,"Configured expiry requirement remains enforced");
 await new SqlCommand("UPDATE OutletMaster SET RequireExpiry=0",connection).ExecuteNonQueryAsync();
 Console.WriteLine("PASS: stale previews, manual batches and retries, historical values, atomic UOM, base-unit protection, discount zero and invalid discounts");
 Console.WriteLine("PASS: transactional routes, aggregation, batches, name-first collision handling, master preservation, retries, changed payload, duplicate invoice, rollback");
}finally{if(server!=null){await server.StopAsync();await server.DisposeAsync();}SqlConnection.ClearAllPools();await new SqlCommand("ALTER DATABASE ["+database+"] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;DROP DATABASE ["+database+"]",master).ExecuteNonQueryAsync();}
